# Project information
site_name: PHP Refresher
site_url: https://arcelopera.github.io/PHPRefresher
site_description: PHP and coding refresher.
site_author: ArceLopera

# Repository
repo_url: https://github.com/ArceLopera/PHPRefresher
repo_name: ArceLopera/PHPRefresher
edit_uri: "" #disables edit button

# Copyright
copyright: Copyright &copy; 2023

# Social media
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ArceLopera
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/carlos-arcelopera
    - icon: fontawesome/brands/github
      link: https://github.com/ArceLopera
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
    - icon: fontawesome/solid/paper-plane
      link: mailto:arcelopera.carlos@gmail.com

# Configuration
theme:
  name: material
  logo: Images/Elephpant.svg
  #<a href="https://iconscout.com/icons/elephant" class="text-underline font-size-sm" target="_blank">Elephant</a> by <a href="https://iconscout.com/contributors/yogiaprelliyanto" class="text-underline font-size-sm" target="_blank">Yaprativa</a>
  favicon: Images/elephant.ico
  palette:
    
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - admonition # alerts
  - pymdownx.details #  collapsible alerts
  - pymdownx.superfences # nest code and content inside alerts
  - attr_list # add HTML and CSS to Markdown elements
  - pymdownx.inlinehilite # inline code highlights
  - pymdownx.keys # show keystroke symbols
  - pymdownx.snippets # insert content from other files
  - footnotes
  - def_list
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

# Plugins
plugins:
  - search


# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Basics: 
     - General: phpRefresh.md
     - Variables and Assignments: 
        - Variables: PR/phpVar1.md
        - Data Types and Casting: PR/phpVar2.md
        - Variable Scope: PR/phpVar3.md
        - Variable Handling: PR/phpVar4.md
     - Constant : PR/phpConst.md
     - Globals : PR/phpSuperGlobals.md
     - Forms : PR/phpForms.md
     - Strings:
        - Basics: PR/phpStr.md
        - Functions: PR/phpStr1.md
     - Numerical: PR/phpNum1.md
     - Math : PR/phpMath1.md
     - Operators : PR/phpOperators1.md
     - Control Flow:
        - Conditionals: PR/phpIF.md
        - Loops: PR/phpLoops.md
     - Keywords: PR/phpKeywords.md
  - Functions: 
     - Built-in:
        - All : Func/phpAll.md
        - Time n Date : 
            - Date/Time: Func/phpDate.md
            - Calendar: Func/phpCalendar.md
        - Regex: Func/phpRegex.md
        - Network: 
            - Cookies: Func/phpCookie.md
            - Sessions: Func/phpSessions.md
            - FTP: Func/phpFTP.md
            - Mail: Func/phpMail.md
        - Filters: Func/phpFilters.md
        - Callback: Func/phpCallback.md
        - JSON: Func/phpJSON.md
        - Errors: Func/phpError.md
        - Exceptions: Func/phpExceptions.md
        - Declare: Func/phpDeclare.md
        - Empty: Func/phpEmpty.md
        - Misc: Func/phpMisc.md
        - Output Control: Func/phpOutput.md
     - User-Defined : 
        - General: Func/phpUserFunc.md
        - Arrow Function: Func/phpArrowFunc.md
        - Generators: Func/phpGenerators.md
  - Data Structures:
     - Array: DS/phpArray.md
     - Iterables: DS/phpIterables.md
  - Classes:
     - OOP: Classes/phpCls.md
     - Constructor : Classes/phpConstructor.md
     - Access Modifiers : Classes/phpModifiers.md
     - Inheritance: Classes/phpInheritance.md
     - Constants: Classes/phpConstants.md
     - Abstract Classes: Classes/phpAbstract.md
     - Interfaces: Classes/phpInterfaces.md
     - Traits: Classes/phpTraits.md
     - Static: Classes/phpStatic.md
     - Namespaces: Classes/phpNamespaces.md
  - Advanced:
     - Include : Adv/phpInclude.md
     - Goto: Adv/phpGoto.md
     - File Management:
            - Filesystem: Adv/phpFile.md
            - Zip: Adv/phpZip.md
     - MySQL : Adv/phpMySql.md
     - XML : Adv/phpXML.md
     - Ajax: Adv/phpAjax.md

